### ISSUE TITLE
TypeError: map.image is undefined

### ISSUE THREAD

**Issue by donmccurdy** [looeee/blackthread_hugo#1]
Seeing an odd error thrown from `gltf-converter.min.js` — 

```
TypeError: map.image is undefined
Stack trace:
processImage@https://blackthread.io/js/vendor//three/examples/js/exporters/GLTFExporter.js:28:198
processTexture@https://blackthread.io/js/vendor//three/examples/js/exporters/GLTFExporter.js:36:53
processMaterial@https://blackthread.io/js/vendor//three/examples/js/exporters/GLTFExporter.js:44:76
processMesh@https://blackthread.io/js/vendor//three/examples/js/exporters/GLTFExporter.js:57:69
...
```
might be an issue in GLTFExporter, but i don't know why `map.image` shouldn't be defined... here's the model:

[tr0052_00.zip](https://github.com/looeee/blackthread_hugo/files/1816607/tr0052_00.zip)

**Comment by looeee** [comment]
This is an error from the GLTF exporter. I've just tested it directly by adding the exporter to the 
https://threejs.org/examples/#webgl_loader_collada example and loading this model, then exporting it. I get the same error there:

`Uncaught TypeError: Cannot read property 'width' of undefined`

I've come across quite a few errors with the exporter, but been unsure of the best way to raise open issues. Basically, I've been testing the converter on all the files in the three.js repo, plus a few of my own. All the files load fine, but quite a few of the loaded models cause errors in the exporter. 

What's the best way to raise the issue? Is it OK if I open an issue and upload the file in the original format?

**Comment by donmccurdy** [comment]
Hm, yeah i think filing issues on the three.js repo would be fine. If there a lot of issues maybe we can set up some simple example to help debug on unminified versions of the loaders and exporter later... thanks!

**Comment by looeee** [comment]
OK, I'll do that. I'll let you handle this model and open issues for any others I come across.

**Comment by donmccurdy** [comment]
Hm, actually this one just worked when I loaded the model in three.js and exported... I'm wondering if it's something about how your converter loads images via drag-and-drop? Are you using the LoadingManager.setURLModifier override, or something else?

**Comment by looeee** [comment]
OK, I found out what the error is. Since the textures are loaded async and don't use the same callback as the model, the exporter can get called before the models textures have loaded and then this error occurs. I'm not sure why it hasn't occurred for any models before this though. 

Easy enough for me to fix on my side, but do you think the exporter should do anything to handle it? 


 I set up a template repo for testing, I'll add more templates as I go:
https://github.com/looeee/glTFExporter-test-templates

If you uncomment this line the  error will trigger:
https://github.com/looeee/glTFExporter-test-templates/blob/master/collada.html#L149

**Comment by looeee** [comment]
Hmm, actually it's being triggered with every model I upload that has separate textures. I must have done something to trigger the export call earlier. 

> Are you using the LoadingManager.setURLModifier override, or something else?

Yes, here: https://github.com/looeee/blackthread_hugo/blob/master/src/js/apps/gltf-converter/components/fileReader.js#L136-L155

You just reminded me that it's a total hack that I meant to update haha!

**Comment by donmccurdy** [comment]
> Since the textures are loaded async and don't use the same callback as the model, the exporter can get called before the models textures have loaded and then this error occurs. ... Easy enough for me to fix on my side, but do you think the exporter should do anything to handle it?

Any idea what the exporter could do other than setting arbitrary timeouts if `map.image` is null? I'd rather avoid that... Maybe `manager.onLoad` will fire when the last image is loaded, then we begin export?

**Comment by looeee** [comment]
Yeah, I wasn't suggesting anything so drastic as using timeouts!
I think it's OK for the exporter to fail here, but it would be good if it does so gracefully since I'm sure I won't be the last person to try and export a model as soon as the `loader.load` callback triggers. 
Either a `console.warn` or even just a comment in the code, something like:

`THREE.GLTFExporter: Couldn't find the image source for a texture map. It's possible that your textures haven't all finished loading yet.`

**Comment by looeee** [comment]
Anyway, I've fixed it on my end for now. Thanks again for letting me know :-)
